
// 自定义颜色常量
export default class ColorConstants {
  static readonly Brand_Color: string = '#EF4F3F';
  static readonly Success_Color: string = '#27BA9B';
  static readonly Warming_Color: string = '#E19A30';
  static readonly Error_Color: string = '#FF4C4C';
  static readonly Main_Text_Color: string = '#2A2929';
  static readonly Border_Color: string = '#D9D9D9';
  static readonly Common_Text_Color: string = '#000000';
  static readonly Sub_Text_Color: string = '#818181';
  static readonly Line_Color: string = '#EEEEEE';
  static readonly PlaceHolder_Color: string = '#C2C1C1';
  static readonly White_Color: string = '#FFFFFF';
  static readonly Background_Color: string = '#F4F4F4';
  static readonly Disabled_Red_Color: string = '#FADCD9';

}