/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Style constants for all features.
 */
export default class StyleConstants {

  static readonly LOGIN_LOGO_HEIGHT: string = '40%';

  static readonly LOGIN_BOTTOM_HEIGHT: string = '60%';

  static readonly FULL_PARENT: string = '100%';

  static readonly BUTTON_WIDTH: string = '90%';

  static readonly GRID_COLUMNS: string = '1fr 1fr 1fr 1fr';

  static readonly GRID_ROWS: string = '1fr 1fr';

  static readonly HOME_GRID_HEIGHT: string = '15.9%';

  static readonly BAR_WIDTH_LG: string = '7.5%' ;

  static readonly BAR_DEFAULT_HEIGHT: string = '7.2%';

  static readonly BAR_HEIGHT_LG: string = '50%';

  static readonly COMMON_WIDTH: string = '95%';

  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH: number = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH: number = 8;

  /**
   *  Left padding of the input box.
   */
  static readonly INPUT_PADDING_LEFT: number = 12;

  /**
   *  Layout weight of number 1.
   */
  static readonly WEIGHT_ONE: number = 1;

  /**
   * Common Spacing of Components.
   */
  static readonly COMMON_SPACE: number = 12;

  /**
   * Logo margin bottom of the parent 50.
   */
  static readonly LOGO_MARGIN_BOTTOM: number = 50;

  /**
   * Item space of the 12.
   */
  static readonly ITEM_SPACE: number = 12;

  /**
   * Grid aspect ratio of the 1.32.
   */
  static readonly GRID_ASPECT_RATIO: number = 1.32;

  /**
   * Swiper count of the 1.
   */
  static readonly SWIPER_COUNT_ONE: number = 1;

  /**
   * Swiper count of the 2.
   */
  static readonly SWIPER_COUNT_TWO: number = 2;

  /**
   * Swiper count of the 3.
   */
  static readonly SWIPER_COUNT_THREE: number = 3;

  static readonly LIST_COLUMN_TWO: number = 2;

  static readonly LIST_COLUMN_THREE: number = 3;

  static readonly LIST_COLUMN_FOUR: number = 4;

  static readonly IMAGE_LIST_SPACE: number = 12;

  static readonly COLUMNS_SM: number = 4;

  static readonly COLUMNS_MD: number = 8;

  static readonly COLUMNS_LG: number = 12;

  static readonly GRID_GUTTER: number = 12;

  static readonly SPAN_SM: number = 4;

  static readonly SPAN_MD: number = 6;

  static readonly SPAN_LG: number = 8;

  static readonly OFFSET_MD: number = 1;

  static readonly OFFSET_LG: number = 2;

  static readonly FULL_WIDTH: string = '100%';

  static readonly FULL_HEIGHT: string = '100%';

  static readonly WEB_HEIGHT: string = '83%';

}